// <auto-generated />
using System;
using LibrarySeatReservation.Web.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibrarySeatReservation.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714085123_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibrarySeatReservation.Web.Models.Entities.DemoUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DemoUsers");

                    b.HasData(
                        new
                        {
                            Id = "user1",
                            CreatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(2760),
                            Name = "小王"
                        },
                        new
                        {
                            Id = "user2",
                            CreatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(2980),
                            Name = "小李"
                        },
                        new
                        {
                            Id = "user3",
                            CreatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(2980),
                            Name = "小张"
                        });
                });

            modelBuilder.Entity("LibrarySeatReservation.Web.Models.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TimeSlot")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "Date");

                    b.HasIndex("SeatId", "Date", "TimeSlot", "Status");

                    b.ToTable("Reservations", t =>
                        {
                            t.HasCheckConstraint("CK_Reservations_TimeSlot", "[TimeSlot] >= 8 AND [TimeSlot] <= 20");
                        });
                });

            modelBuilder.Entity("LibrarySeatReservation.Web.Models.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Features")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5720),
                            Features = "有电源",
                            IsAvailable = true,
                            Location = "一楼靠窗",
                            Name = "A-01",
                            UpdatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5820)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5910),
                            Features = "有电源",
                            IsAvailable = true,
                            Location = "一楼靠窗",
                            Name = "A-02",
                            UpdatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5910)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5910),
                            Features = "有台灯",
                            IsAvailable = true,
                            Location = "一楼靠窗",
                            Name = "A-03",
                            UpdatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5910)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5910),
                            Features = "有电源",
                            IsAvailable = true,
                            Location = "二楼安静区",
                            Name = "B-01",
                            UpdatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5910)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5920),
                            IsAvailable = true,
                            Location = "二楼安静区",
                            Name = "B-02",
                            UpdatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5920)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5920),
                            Features = "有电源",
                            IsAvailable = true,
                            Location = "二楼安静区",
                            Name = "B-03",
                            UpdatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5920)
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 4,
                            CreatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5920),
                            Features = "有电源、有白板",
                            IsAvailable = true,
                            Location = "三楼讨论区",
                            Name = "C-01",
                            UpdatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5920)
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 4,
                            CreatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5920),
                            Features = "有电源",
                            IsAvailable = true,
                            Location = "三楼讨论区",
                            Name = "C-02",
                            UpdatedAt = new DateTime(2026, 7, 14, 8, 51, 23, 668, DateTimeKind.Utc).AddTicks(5920)
                        });
                });

            modelBuilder.Entity("LibrarySeatReservation.Web.Models.Entities.Reservation", b =>
                {
                    b.HasOne("LibrarySeatReservation.Web.Models.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibrarySeatReservation.Web.Models.Entities.DemoUser", "DemoUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DemoUser");

                    b.Navigation("Seat");
                });
#pragma warning restore 612, 618
        }
    }
}
